### PR TITLE
Start script, docker, consul

### PR DESCRIPTION
**Pull request by ghost**
- Dockerization
- Script de lancement npm
- Configuration pour consul

### CODE REVIEW

**Comment by marysaka** [comment]
This is a minor change, I will do it myself. Also I don't like the way you have done the dockerization.

**Comment by jeremylvln** [comment]
Also, I want this project to be as simple as possible. This is why I don't understand the utility of Consul in this case. We can check ourself if the application is up or down. The application is currently running under Forever who keep the application up and functionnal.

**Comment by ghost** [comment]
I was supposing the application will need to scale as easier as possible if multiple servers are going to use the database as the same time ^^

**Comment by jeremylvln** [comment]
I understand what you're saying but what is the utility of consule in this case? It's pretty useless. Also, deploy the application on multiple servers is such a bad idea because the database HAS to be updated only on my provided because it'll update this repository too!

To conlcude, it's better to imagine only one instance of the application, I mean mines and create a correct API implementation including cache into memory or RAM based database like Redis.

**Pull request closed without merging**
